name: 'Feishu Bot Webhook Action'
description: '发送消息到飞书机器人的 GitHub Action'
author: 'XRSec'

inputs:
  FEISHU_BOT_WEBHOOK:
    description: '飞书机器人的 webhook URL'
    required: true
  FEISHU_BOT_SIGNKEY:
    description: '飞书机器人的签名密钥（可选）'
    required: false
  MSG_TEXT:
    description: '要发送的 Markdown 消息内容。如果不为空，将发送简化的 Markdown 卡片；否则发送 GitHub 事件模板消息'
    required: true
  DRY_RUN:
    description: '仅打印将要发送的消息而不实际发送（true/1）'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'message-circle'
  color: 'blue'
